name = "Default"
background = { r = 0.117, g = 0.117, b = 0.117, a = 1.0 }
foreground = { r = 0.8, g = 0.8, b = 0.8, a = 1.0 }
cursor = { r = 1.0, g = 1.0, b = 1.0, a = 1.0 }
selection = { r = 0.149, g = 0.31, b = 0.471, a = 1.0 }
black = { r = 0.0, g = 0.0, b = 0.0, a = 1.0 }
red = { r = 0.804, g = 0.192, b = 0.192, a = 1.0 }
green = { r = 0.051, g = 0.737, b = 0.475, a = 1.0 }
yellow = { r = 0.898, g = 0.898, b = 0.063, a = 1.0 }
blue = { r = 0.141, g = 0.447, b = 0.784, a = 1.0 }
magenta = { r = 0.737, g = 0.247, b = 0.737, a = 1.0 }
cyan = { r = 0.067, g = 0.659, b = 0.804, a = 1.0 }
white = { r = 0.898, g = 0.898, b = 0.898, a = 1.0 }
bright_black = { r = 0.4, g = 0.4, b = 0.4, a = 1.0 }
bright_red = { r = 0.945, g = 0.298, b = 0.298, a = 1.0 }
bright_green = { r = 0.086, g = 0.776, b = 0.047, a = 1.0 }
bright_yellow = { r = 0.961, g = 0.961, b = 0.263, a = 1.0 }
bright_blue = { r = 0.231, g = 0.557, b = 0.918, a = 1.0 }
bright_magenta = { r = 0.839, g = 0.439, b = 0.839, a = 1.0 }
bright_cyan = { r = 0.161, g = 0.722, b = 0.859, a = 1.0 }
bright_white = { r = 1.0, g = 1.0, b = 1.0, a = 1.0 }
tab_bar_background = { r = 0.176, g = 0.176, b = 0.176, a = 1.0 }
tab_bar_active = { r = 0.117, g = 0.117, b = 0.117, a = 1.0 }
tab_bar_inactive = { r = 0.216, g = 0.216, b = 0.216, a = 1.0 }
